version: "3.8"

services:
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:latest

        RUN rm /etc/nginx/conf.d/default.conf

        # Copy the custom configuration file into the container
        COPY ./nginx.conf /etc/nginx/conf.d
    ports:
      - 80:80