version: "3.8"

services:
  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:latest

        RUN rm /etc/nginx/conf.d/default.conf

        # Copy the custom configuration file into the container
        COPY ./nginx.conf /etc/nginx/conf.d
    ports:
      - 80:80

  login-app:
    container_name: login-app
    build: 
      context: ../login-app
      dockerfile_inline: | 
        FROM node:alpine
        WORKDIR /app
        COPY . .
        RUN npm install
        CMD ["npm", "run", "dev"]
    ports:
      - 3000:3000

  ids-server:
    container_name: ids-server
    build: 
      context: ../ids-server
      dockerfile_inline: |
        FROM node:alpine
        WORKDIR /app
        COPY . .
        RUN npm install
        CMD ["node", "server.js"]
    ports:
      - 7777:7777
    volumes:
      - ../important:/important
  
  ids-app:
    container_name: ids-app
    build: 
      context: ../ids-app
      dockerfile_inline: | 
        FROM node:alpine
        WORKDIR /app
        COPY . .
        RUN npm install
        CMD ["npm", "run", "dev"]
    ports:
      - 7778:7778